### PR TITLE
Changed Styling Based on New Logo

### PR DESCRIPTION
**Pull request by alexisbarnes**
Open to feedback on how it looks!

### CODE REVIEW

**Comment by SchaeStewart** [comment]
@alexisbarnes I think this looks pretty good, can you attach some screenshots of the changes?

**Comment by alexisbarnes** [comment]
@SchaeStewart Ah yes sorry.
 
Screen Shot 2021-02-16 at 3 33 32 PM

Screen Shot 2021-02-16 at 3 33 57 PM

Screen Shot 2021-02-16 at 3 34 19 PM

**Review by mcelestini — APPROVED** [review]
awesome!

**Review by SchaeStewart — APPROVED** [review]
Looks good to me

**Review by funkybunch — APPROVED** [review]
Looks great!  Thanks @alexisbarnes!

**Pull request merged**
