### PR TITLE
[109] Server Side Table Sorting

### LINKED ISSUE #109: Rewrite Table component to support sort and filter API endpoints: prove concept with candidates page
Blocked on #90, #92, #93

Currently, sorting and filtering work on the front-end using `react-table`. We're moving sorting and filtering functionality to backend API calls. The Table component and hooks need to be updated to utilize the new sorting feature.

### PR DESCRIPTION
**Pull request by mcelestini**
This PR adds a `lastQuery` object to all of our components, where we track all of the parameters we used with our last api requests. That way, when a change is made to sorting, offset, filtering, etc. all we have to do is spread `lastQuery` and update the appropriate query. Here's an example:
https://github.com/ncopenpass/CampaignFinance/pull/176/files#diff-bdfe4b162859155cadb313cc6ea6539a88fc8def4cd976f89aaf0b8f6c428ec1R33-R35

Check out the gifs of sorting working on our 3 current tables

***Candidate Page***
Kapture 2020-11-11 at 14 01 47

***Search Results Page***
Kapture 2020-11-11 at 14 01 06

Fixes #109

### CODE REVIEW

**Review by alexisbarnes — COMMENTED** [review]
Are you able to add the up and down arrows to those columns that can be filtered on the default table view (similar to below - the arrows can be more consistent with what you already have)? Just want it to clear to the user that those columns can be filtered.

Screen Shot 2020-11-13 at 7 18 05 PM

**Comment by SchaeStewart** [comment]
@mcelestini Bumping this. Any update for Alexis?

**Comment by mcelestini** [comment]
@SchaeStewart @alexisbarnes just updated the code with new images for sorting, take a look below

Kapture 2021-01-26 at 13 43 11

**Review by alexisbarnes — APPROVED** [review]
Thanks for adding the arrows @mcelestini!!

**Review by SchaeStewart — APPROVED** [review]

**Pull request merged**
