### PR TITLE
Remove table filter/sort and add table size dropdown for MVP

### LINKED ISSUE #149: Filters should be removed for the MVP demo
Current table filters don't work the way they're intended to. We're deferring new filtering logic/workflow until after the demo. For the time being we should remove filters from the tables.

### PR DESCRIPTION
**Pull request by Dafondo**
Resolves #149 

Changes:
1. Hid table filter and sort because they don't function as intended. Filtering/sorting will be revisited after MVP in #109.
1. Created table size dropdown that lets user's choose how many results to show in the table.

Considerations:
1. We're using [`react-table`](https://github.com/tannerlinsley/react-table) for the base Table component, but we've also custom built some of our pagination logic (that can be replaced with `react-table` hooks). There's some additional table logic we need in the future (eg. table sizing, additional pagination logic), that `react-table` also has hooks for. After the MVP demo, we should consider switching our existing custom pagination implementation to `react-table` pagination hooks, so we don't have to continue building custom implementations when they already exist in `react-table`.

### CODE REVIEW

**Comment by alexisbarnes** [comment]
The app crashes when I use the quick-search buttons.

Screen Shot 2020-09-13 at 6 13 58 PM

**Comment by Dafondo** [comment]
Should be fixed now! Thanks for pointing that out.

**Review by alexisbarnes — APPROVED** [review]

**Comment by alexisbarnes** [comment]
Don't merge this yet... @SchaeStewart do you want to continue with hiding the filters or is someone fixing them?

**Review by alexisbarnes — CHANGES_REQUESTED** [review]
Looks good but don't merge this yet... @SchaeStewart do you want to continue with hiding the filters or is someone fixing them?

**Comment by SchaeStewart** [comment]
@alexisbarnes let's wait for now, unless this is blocking something else. Marc is still working on the filtering. If it's not done tonight/early tomorrow. We can merge this in

**Comment by alexisbarnes** [comment]
Sounds good!

**Review by mcelestini — APPROVED** [review]
:shipit:

**Review by SchaeStewart — APPROVED** [review]
I'm going to go ahead and merge this for the demo tonight

**Pull request merged**
