### PR TITLE
use react routing for 'back' link on  candidate page

### PR DESCRIPTION
**Pull request by brandon-irl**
fixes issue #132

Do we want to use browser history though?

### CODE REVIEW

**Comment by SchaeStewart** [comment]
@brandon-irl What do you mean by `browser history`? Is there another way of doing this that might be better?

**Comment by brandon-irl** [comment]
> 
> 
> @brandon-irl What do you mean by `browser history`? Is there another way of doing this that might be better?

`BrowserRouter.history` uses the HTML5 history API and is kept in sync with it, so calling back is the same as using the back button on the browser. Better way may be to implement a breadcrumb or something

**Review by Dafondo — APPROVED** [review]
I think this is good for now. At some point (after the MVP demo) we need to think about how to best handle history when the user clicks through multiple links (eg. Search -> Candidate -> Specific Contributor on Candidate page -> ...)

**Comment by SchaeStewart** [comment]
My only concern is if someone visits the Candidate Page directly (ie via the direct url without searching) the back button would take them away from the site

**Comment by Dafondo** [comment]
Good point. Maybe we can render the back link dynamically based on where the user is coming from?

**Comment by brandon-irl** [comment]
> 
> 
> Good point. Maybe we can render the back link dynamically based on where the user is coming from?

This would be the breadcrumb

**Review by mcelestini — APPROVED** [review]

**Review by SchaeStewart — CHANGES_REQUESTED** [review]
Let's implement some sort of bread crumb and wait until after the demo tomorrow before merging

**Comment by brandon-irl** [comment]
@SchaeStewart changed it so that the search link passes a crumb representing it's path to the candidate page, which uses it to push a new location onto the history stack. Also conditionally looks at the crumb when decided whether or not to render the link. This might cause weird/unintended behavior when using the browser controls though so I don't know if it's what we want

**Comment by brandon-irl** [comment]
We could still use the `history.goBack()` and keep the browser nav while also conditionally showing the link. Test it out and let me know.

**Comment by SchaeStewart** [comment]
This looks good to me @Dafondo @mcelestini  What do y'all think?

**Comment by Dafondo** [comment]
Works well on my end. @brandon-irl do you know of any specific edge cases that we should look at?

**Comment by SchaeStewart** [comment]
If you refresh the page the back link does get lost @Dafondo

**Comment by brandon-irl** [comment]
> 
> 
> If you refresh the page the back link does get lost @Dafondo

Also if you go back and forward again I believe

**Comment by SchaeStewart** [comment]
I think we can add a future improvement to store the search query in the url that way on refresh the link will show, but I think we are good to merge this now

**Review by SchaeStewart — APPROVED** [review]

**Pull request merged**
